### PR TITLE
Updating CONTRIBUTING.md 

### PR DESCRIPTION
**Pull request by Supun94**
PR for issue #7

### CODE REVIEW

**Comment by joestrong** [comment]
The PR is set to merge into develop, but your branch is branched from master.

Can you pull my latest develop branch, and rebase your commits onto there?

**Comment by Supun94** [comment]
@joestrong Update the branch with latest changes hope you can merge the PR now ;)

**Comment by joestrong** [comment]
Yep good 👍

**Comment by Supun94** [comment]
Thanks @joestrong :)

**Pull request merged**
